- name: Setup
  hosts: mine
  vars:
    username: lawrence
  tasks:
    - name: Terminal DNF software
      ansible.builtin.dnf5:
        name: 
          - neovim
          - fish
          - tmux
          - uv
        state: present
      become: yes


    - name: GUI DNF Software
      ansible.builtin.dnf5:
        name: 
          - alacritty
          - fedora-workstation-repositories
          - google-chrome-stable
          - steam
        state: present
      become: yes

    - name: Nvidia DNF Software
      ansible.builtin.dnf5:
        name: 
          - akmod-nvidia
          - xorg-x11-drv-nvidia-cuda
        state: present
      become: yes


    - name: Add Flathub remote repository
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: user

    - name: Flatpak GUI Software
      become: no
      community.general.flatpak:
        name: 
          - org.telegram.desktop
          - md.obsidian.Obsidian
          - com.mikrotik.WinBox
          - com.usebottles.bottles
          - com.belmoussaoui.Authenticator
        state: present
        remote: flathub
        method: user

    - name: Setup fish for user
      block:
      - name: Find the absolute path of fish
        ansible.builtin.command: which fish
        register: fish_path
        changed_when: false
        failed_when: fish_path.rc != 0

      - name: Ensure fish is registered in /etc/shells
        ansible.builtin.lineinfile:
          path: /etc/shells
          line: "{{ fish_path.stdout.strip() }}"
          create: true
          mode: '0644'
        become: yes

      - name: Set fish as the default login shell for the user
        ansible.builtin.user:
          name: "{{ username }}"
          shell: "{{ fish_path.stdout.strip() }}"
        become: yes

